version: '3'

services:
  nest-app:
    container_name: nest
    build:
      context: ..
      dockerfile: example/infra/nest/Dockerfile
    volumes:
      - ../:/app
      - /app/example/node_modules
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: testdb

volumes:
  pg_data:
